### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by FrostBird347** [detomon/bliplay-wasm#1]
I recently downloaded and implemented `bliplay.js`, `bliplay.wasm`, `controller.js` and `app.js` into my own (currently private) web project so I could play custom `.blip` files instead of needing the client to download far larger `.wav` files.
However, it was only after I got it all set up and functioning when I realised that, unlike the bliplay repo, this one has no licence specified.

Is it possible for me to use this code in my own project, provided that I give credit, or would you rather me build my own web assembly version of bliplay?

**Comment by detomon** [comment]
Thanks for letting me know! That was an oversight, the license is now also MIT. I also updated the `bliplay` submodule to the newest version and recompiled `bliplay.wasm` and the corresponding `bliplay.js`. And there are [some changes](https://github.com/detomon/bliplay-wasm/commit/5a7e26029e6936d7d984735bd480eb39bdb34100) in `controller.js` which fix a problem when compiling with the newest `emcc` version when loading `.wav` files.
